version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/base:2024.01

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: echo "build"
  test:
    executor: my-executor
    steps:
      - checkout
      - run: echo "test"
  deploy:
    executor: my-executor
    steps:
      - checkout
      - run: echo "deploy"

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold